name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Test and deploy
    runs-on: ubuntu-latest
    concurrency: ${{ github.repository }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Java Temurin 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'temurin'
          cache: 'maven'
      - name: Test with Maven
        run: mvn test
      - name: Increment version
        id: increment-version
        uses: RichardInnocent/semantic-versioning-maven@v0.0.34
        with:
          access-token: ${{ github.token }}